alias st='git log --oneline -n 13; git status'
alias stf='git log --oneline ; git status'
alias sw='git show'
alias gd='git diff'
alias ch='git checkout'
alias tag='git tag'
alias gb='git branch '
alias che='git checkout experemental; st'
alias chm='git checkout master; st'
alias chs='git checkout stable; st'
alias gbe='git branch experemental; st'
alias gbs='git branch stable; st'
alias gbed='chm; git branch -d experemental; st'
alias gme='chm; git merge experemental; st'
alias gms='chs; git merge master; st'
alias gmm='che; git merge master; st'
alias gh='git push; st'
alias ghe='git push origin experemental; st'
alias ghs='git push origin stable; st'
alias gad='git add . ; st'
alias gadi='git add -i'
alias gitresetsoft-1='git reset --soft HEAD~1; st'
#resets everything to its state in priviuse  HEAD.
alias gitrst='git reset -hard; st'
#resets everything to its state in HEAD.
alias gtr='git reflog'
#showe udelete
alias grm='git rm --cached'
alias gig='echo $1 >> .gitignore'
alias keyup='eval $(ssh-agent -s)'
alias acc='st; git commit -a -m'
alias ac='git status; git commit -a; git log --oneline; git status;'
alias acae='git commit --amend; git log --oneline; git status;'
alias aca='git commit --amend --no-edit; git log --oneline; git status;'
alias glog='git log --oneline'
alias glogp='git log --pretty=oneline'
alias glogt='git log --graph --oneline --decorate --all'
alias glogc='git log --name-status'
alias versio_control_dir='cd D:/\Development/\version-control/\'
alias tutorial_ddt_py='cd D:/\Development/\version-control/\GitHub/\TDD-Python/\'
alias act_vir='source virtualenv/Scripts/activate'


#activate virtual envoremen if it is in starting dir
act_vir
